#que parta de la imagen de ubuntu version 22.04
# que tenga instalado un vim y un  nginx
# y al final ejecute un /bin/bash
# aplicar cambios en el docker-compose para que use esta imagen
# ne lugar de usar la imagen orinal anterior
# en el docker compose llamad a esta imagen image-daw-12


FROM ubuntu:22.04

RUN apt-get update && apt-get install -y nginx vim 

CMD ["/bin/bash"]